#include <iostream>
#include <windows.h>
#include <tlhelp32.h>
#include <thread>
#include <string>
#include <codecvt>
#include <locale>
#include "winnls.h"
#include "shobjidl.h"
#include <Commdlg.h>
#include "objbase.h"
#include "objidl.h"
#include "shlguid.h"
#include <filesystem>
#include <fstream>
#include <stdio.h>
#include <sys/types.h>
#include <cstdio>
#include <string_view>